language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
before_script:
  - npm install -g eclint
  - npm run eclint
  - npm install -g eslint
  - npm run eslint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
